In [ ]:
# Create a numpy array of size 10, filled with zeros

In [23]:
import sys
from numpy import *

In [21]:
a = zeros(10, dtype=int)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Create a numpy array with values ranging from 10 to 49

In [24]:
b = arange(10, 49)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [ ]:
#Create a numpy matrix of 2*2 integers, filled with ones.

In [31]:
c = array([[2] *2] * 2)
c
c.shape

(2, 2)

In [ ]:
#Create a numpy matrix of 3*2 float numbers, filled with ones

In [33]:
d = array([[1] * 2] * 3)
d

array([[1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [39]:
X = arange(4, dtype=int)
X
Y= ones(X.shape)
Y

array([1., 1., 1., 1.])

In [40]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.
X = array([[1,2,3], [4,5,6]], dtype=int)
Y=zeros(X.shape)
X, Y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[0., 0., 0.],
        [0., 0., 0.]]))

In [41]:
#Create a numpy matrix of 4*4 integers, filled with fives.
x = ones([4,4], dtype=int) * 5
x

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [42]:
#Given the X numpy matrix, create a new numpy matrix with the
#same shape and type as X, filled with sevens.
X = array([[2,3], [6,2]], dtype=int)
ones_like(X) * 7

array([[7, 7],
       [7, 7]])

In [43]:
#Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.
identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])