In [2]:
import sys
from numpy import *

In [6]:
a = array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [7]:
a.dtype

dtype('int32')

In [10]:
A = array([
    [1, 2, 3],
    [4, 5, 6]
])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
A.shape

(2, 3)

In [13]:
A.ndim, A.size

(2, 6)

In [14]:
c = array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])
c[2][1]

8

In [15]:
c[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [21]:
d=array([
    [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]
])   
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
d[1]=[10, 10, 10]
d
d[2]*=10
d
d[0]=[88]
d

array([[ 88,  88,  88],
       [ 10,  10,  10],
       [700, 800, 900]])

In [29]:
d.sum(), d.mean(), d.std(), d.var()

(2694, 299.3333333333333, 358.56628087116303, 128569.77777777778)